### ISSUE TITLE
Use ssl transport if url is https

### ISSUE THREAD

**Issue by awr** [awr/KafkaClient#25]
Fall back to default ssl setup if none configured and url specified is in the format http://

**Comment by ligu** [comment]
I think this is misleading.
Actually I would completely remove the whole http/https thing from the server address, because the kafka client-server protocol is not http at all, it's a proprietary binary protocol over tcp sockets.

**Comment by awr** [comment]
You know ... that's a much better idea!

It was in there before and I just ran with it -- but better to remove the http altogether.
