### ISSUE TITLE
Proper support for Consumer Groups

### ISSUE THREAD

**Issue by awr** [awr/KafkaClient#9]
This will require heartbeats, group join semantics, etc.

**Comment by tsibelman** [comment]
Hi just wanted to let you know that I think it super cool that you took it on yourself to implement proper Kafka client for .net

**Comment by awr** [comment]
Thanks -- much appreciated! :)

**Comment by awr** [comment]
Finally realized that (in some scenarios?) there is a limit on the amount of parallelism *on the server* when dealing with consumer group stabilization. And this is based on the number of connections used to update state for a group.

**Comment by awr** [comment]
The solution is to ensure that each member of the group (for group control requests) uses a separate connection. I've taken a stab at this via the router -- this way we still get to cache shared details about assignment through the same router, and different groups can use the same connections. It also enables other operations to leverage these existing connections (so as to reduce port exhaustion on the kafka servers).

The unfortunate side effect is a fair bit of added complexity inside the router. I'll need to add a good number of tests to help deal with the complexity.
